services:
  netbox:
    image: netbox:latest-plugins
    pull_policy: never
    ports:
      - 8000:8080
    build:
      context: .
      dockerfile: Dockerfile-Plugins
  netbox-worker:
    ports: []   # le worker hérite de 8000:8080 via l'ancre YAML : on le neutralise
    image: netbox:latest-plugins
    pull_policy: never
